### ISSUE TITLE
Cursor disappears, if programm exits with panic()

### ISSUE THREAD

**Issue by DanglmaierSimon** [chrboe/oebb-cli#1]
If the programm exits with `panic()`, the cursor is hidden, until a command is entered, which exits normally.

Steps to reproduce:

1. Run `oebb-cli search Wien Linz -t 24:00`, Cursor is now hidden, since the programm crashes (time cannot be parsed).
2. To get the cursor back, run a different query, that exits normally. For example `oebb-cli search Wien Linz -t 00:00`

**Comment by chrboe** [comment]
Fixed, thanks
